# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'EMCalender' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for EMCalender
    pod 'Masonry', '~> 1.1.0'
    pod 'MLeaksFinder', '~> 1.0.0'
end

target 'EMExtension' do
    pod 'Masonry', '~> 1.1.0'
    
end
